@startuml
autonumber


actor user
participant "Оркестратор процессов" as op
participant "Сервис заявок" as sz
participant "Сервис расчета стоимости" as srs
participant "Сервис проверки устройств" as spu
participant "Сервис учета устройств" as suu
participant "Сервис поиска нового владельца" as spnv
participant "Сервис платежей" as sp
participant "Оркестратор доставки" as od


== Постановка устройства на учет ==

op -> spu: Тестирование устройства
spu --> op: HTTP 200 OK
op -> srs: Финальный расчет стоимости
srs --> op: HTTP 200 OK
op -> sp: Отправить клиенту денежные средства за устройство
sp --> op: Платеж принят в обработку
op -> suu: Внести запись о приеме устройства на склад
suu --> op: HTTP 200 OK
op -> spnv: Запуск процесса поиска \nи принятие решения о новом владельце
spnv --> op: HTTP 200 OK

== Завершение процесса учета ==

spnv -> op: Устройство доставлено в логистический пункт Авито
op --> spnv: HTTP 200 OK
od -> op: Владелец получил устройство
op --> od: HTTP 200 OK
sp -> op: Поступление платежа
opt Истек таймаут ожидания платежа
    op -> op: Отправка события на ручной разбор
end
op -> op: Сверка баланса
alt Баланс не сошелся с количеством устройств
    op -> op: Отправка события на ручной разбор
else Баланс сошелся
    op -> op: Завешение процесса
end



@enduml