@startuml
autonumber


actor user
participant "Сервис заявок" as sz
participant "Сервис расчета стоимости" as srs
participant "Хранилище контента" as hk
participant "Оркестратор процессов" as op


== Процесс обращения клиента ==

user -> sz: Создание заявки
sz --> user: Заявка создана
sz -> sz: Сохранение заявки в БД
sz -> hk: Сохренение прикрепленных фотографий
hk --> sz: HTTP 200, id файла
sz -> srs: Предварительный расчет суммы
srs --> sz: HTTP 200, предварительная сумма вознаграждения
sz -> op: Запуск процесса постановки устройства на учет
op --> sz: HTTP 200, процесс запущен

== Обновление статуса заявки ==

op -> user: Статус заявки обновился

== Получение выплаты клиентом ==

op -> op: Зачисление денег на счет клиента
op -> user: Уведомление клиента что деньги отправлены


@enduml