@startuml
autonumber


actor Водитель
participant "Оркестратор процессов" as op
participant "Оркестратор доставки" as od
participant "Сервис учета устройств" as suu
participant "Сервис поиска нового владельца" as spnv


== Процесс доставки или возврата устройства ==
spnv -> od: Запуск процесса доставки
od --> spnv: HTTP 200 OK
od -> od: Создание маршрута доставки
od -> Водитель: Оповещение отдела логистики о маршруте
od -> suu: Устройство выбыло со склада
suu --> od: HTTP 200 OK
Водитель -> Водитель: Доставка до пункта Авито
Водитель -> od: Устройство доставлено в логистический пункт Авито
od -> op: Устройство доставлено в \nлогистический пункт Авито



@enduml